# Generated by Django 5.2.7 on 2025-12-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_categoryid_product_genreid_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='addedDate',
            new_name='productImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='genreID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.genre'),
        ),
    ]
