# Generated by Django 5.2.7 on 2025-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_orignalprice_alter_blog_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orignalPrice',
            new_name='originalPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
