# Generated by Django 5.2.7 on 2025-12-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_orignalprice_product_originalprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='myapp.category'),
        ),
    ]
