# Generated by Django 5.2.7 on 2025-12-21 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_billingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
